INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('weaponmag', 'Extended Mag', -1, 0, 1),
	('compensator', 'Compensator', -1, 0, 1),
	('mk2scope', 'MK2 Scope', -1, 0, 1),
	('yusuf', 'Gold Skin', -1, 0, 1),
	('scoperifle', 'Scope Rifles', -1, 0, 1),
	('vipskinbutterfly', 'VIP Skin Butterfly', -1, 0, 1),
	('knuckleskinlove', 'Knuckle Skin LOVE', -1, 0, 1),
	('mediumscope', 'Medium Scope', -1, 0, 1),
	('largescope', 'Large Scope', -1, 0, 1),
	('holoscope', 'Holographic Sight', -1, 0, 1),
	('platskinpistol50', 'Platinum Pistol 50 Skin', -1, 0, 1),
	('woodhpistolskin', 'Wood Heavy Pistol Skin', -1, 0, 1),
	('woodrifleskin', 'Wood Rifles Skin', -1, 0, 1),
	('skullrifleskin', 'Skull Rifles Skin', -1, 0, 1),
	('zebrarifleskin', 'Zebra Rifles Skin', -1, 0, 1),
	('boomrifleskin', 'Boom Rifles Skin', -1, 0, 1),
	('tacticalmuzzlebrake', 'Tactical Muzzle Brake', -1, 0, 1),
	('knucleskinpimp', 'Knuckle Skin PIMP', -1, 0, 1),
	('knuckleskinballas', 'Knuckle Skin Ballas', -1, 0, 1),
	('knuckleskindollar', 'Knuckle Skin Dollar', -1, 0, 1),
	('knucleskindiamond', 'Knuckle Skin Diamond', -1, 0, 1),
	('knuckleskinhate', 'Knuckle Skin Hate', -1, 0, 1),
	('knuckleskinplayer', 'Knuckle Skin Player', -1, 0, 1),
	('knuckleskinvagos', 'Knuckle Skin Vagos', -1, 0, 1),
	('flashlightweapon', 'Flashlight Weapons', -1, 0, 1),
	('weaponsuppressor', 'Suppressor', -1, 0, 1)